In [3]:
import pandas as pd 
df_fake = pd.read_csv('../data/fake.csv')
df_true = pd.read_csv('../data/true.csv')

In [4]:
df_fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [5]:
df_true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [43]:
df_fake['label'] = 0
df_true['label'] = 1

In [51]:
df_fake.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [10]:
df_fake = df_fake.drop(df_fake.index[21418:-1])

In [11]:
df_true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

#### Concatenate and shuffle the dataset after concatenating

In [12]:
data = pd.concat([df_fake, df_true], axis=0)
data = data.sample(frac=1).reset_index(drop=True)
data.head()

,title,text,subject,date
0,"Immigration overhaul backers sing, dance, chan...","WASHINGTON (Reuters) - Dancing, singing, chant...",politicsNews,"April 18, 2016"
1,Lifetime Republican Voter Thanks President Ob...,"Republican lawmakers hate Obamacare, but it s ...",News,"March 4, 2016"
2,U.S. commerce chief says he is likely to dives...,WASHINGTON (Reuters) - U.S. Commerce Secretary...,politicsNews,"November 6, 2017"
3,President Obama Defends Kaepernick’s Protest ...,Conservatives are throwing a collective hissy ...,News,"September 5, 2016"
4,"German coalition talks stumble on migration, c...",BERLIN (Reuters) - Three German parties resign...,worldnews,"October 26, 2017"

In [16]:
from src.data_utils import load_data
data = load_data('data/fake.csv', 'data/true.csv')
data.head()

                                                text  label
0  there have recently been allegations claiming ...      0
1  it s too early to endorse hillary  what s al g...      0
2  barack obama and first lady  michelle  attende...      0
3  ottawa  reuters    canada will make an announc...      1
4  new york  reuters    the mayor of paterson  ne...      1

In [15]:
cd ..

c:\Users\My Pc\Desktop\project ML

In [17]:
pwd

'c:\\Users\\My Pc\\Desktop\\project ML'