In [1]:
import pandas as pd 
df_fake = pd.read_csv('../data/fake.csv')
df_true = pd.read_csv('../data/true.csv')

In [4]:
df_fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [8]:
df_true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [9]:
df_fake['label'] = 0
df_true['label'] = 1

In [10]:
df_fake.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [2]:
df_true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

#### Concatenate and shuffle the dataset after concatenating

In [18]:
data = pd.concat([df_fake, df_true], axis=0)
data = data.sample(frac=1).reset_index(drop=True)
data.head()

,title,text,subject,date,label
0,REVEALED: Who Gave Democratic Emails To Wikile...,While all of the mainstream media and anonymou...,left-news,"Dec 19, 2016",0
1,Egyptian billionaire denounces Saudi corruptio...,ROME (Reuters) - Egyptian billionaire business...,worldnews,"December 1, 2017",1
2,"After Being Handed Yet Another Court Loss, Tr...",Donald Trump hates losing. Not because it s a ...,News,"April 26, 2017",0
3,COMCAST GIVES EMPLOYEES Day Off To PROTEST TRU...,Wow! I was just getting ready to switch our TV...,left-news,"Feb 3, 2017",0
4,"Congo military plane crashes in Kinshasa, kill...",KINSHASA (Reuters) - A military cargo plane cr...,worldnews,"September 30, 2017",1

In [ ]:
from src.data_utils import load_data
data = load_data('../data/fake.csv', '../data/true.csv')
data.head()

In [ ]:
cd "c:\Users\My Pc\Desktop\project ML new"

c:\Users\My Pc\Desktop\project ML new

In [6]:
from src.data_utils import load_data
data = load_data('data/fake.csv', 'data/true.csv')
data.head()

                                                text  label
0  washington  reuters    democratic presumptive ...      1
1  we reported earlier today that  chuck and nanc...      0
2   century wire says the field is now clear for ...      0
3  jerusalem  reuters    israel said on sunday it...      1
4  there s so much to know in order to understand...      0